services:
  app:
    container_name: react-app-server
    image: lincenying/images-mmf-blog-vite-react:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8088:80'
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
