services:
  frontend:
    container_name: images-mmf-blog-vite-react
    image: lincenying/images-mmf-blog-vite-react:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8088:80"
    depends_on:
      - api

  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017

  api:
    image: lincenying/api-server:1.0.1
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4008:4000
    depends_on:
      - mongo
