services:
  app:
    container_name: react-app-server
    image: lincenying/images-mmf-blog-vite-react:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8088:80'
    networks:
      - webnet

  mongo:
    container_name: react-mongo-server
    image: mongo:4.0
    restart: always
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  api:
    container_name: react-api-server
    image: lincenying/api-server:${APITAG}
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4008:4000
    depends_on:
      - mongo
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
